// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX9rF8O2XLp_ggShaUk4NwXdqXc72YZFo',
    appId: '1:723528080405:web:f9789f61b377e9b3e0c21c',
    messagingSenderId: '723528080405',
    projectId: 'simplescratch-bcfe9',
    authDomain: 'simplescratch-bcfe9.firebaseapp.com',
    storageBucket: 'simplescratch-bcfe9.appspot.com',
    measurementId: 'G-DDM7XTQR2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAUIlhozckgEptzvWrZDRPF4ss-w0FFmI',
    appId: '1:723528080405:android:ed96bd01b7281c9ae0c21c',
    messagingSenderId: '723528080405',
    projectId: 'simplescratch-bcfe9',
    storageBucket: 'simplescratch-bcfe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgoPnAKpn9DNcrJsuSwjwZBswK79wMTJw',
    appId: '1:723528080405:ios:fdc8ee900f35c5d1e0c21c',
    messagingSenderId: '723528080405',
    projectId: 'simplescratch-bcfe9',
    storageBucket: 'simplescratch-bcfe9.appspot.com',
    iosClientId: '723528080405-10843g967662isg4b6pcr1f6fu9kk3ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleScratch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgoPnAKpn9DNcrJsuSwjwZBswK79wMTJw',
    appId: '1:723528080405:ios:fdc8ee900f35c5d1e0c21c',
    messagingSenderId: '723528080405',
    projectId: 'simplescratch-bcfe9',
    storageBucket: 'simplescratch-bcfe9.appspot.com',
    iosClientId: '723528080405-10843g967662isg4b6pcr1f6fu9kk3ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleScratch',
  );
}
